package pack;
// Generated 22 mai 2024 11:38:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Depart generated by hbm2java
 */
public class Depart  implements java.io.Serializable {


     private Integer id;
     private String nomDept;
     private String chefDept;
     private Set employees = new HashSet(0);

    public Depart() {
    }

    public Depart(String nomDept, String chefDept, Set employees) {
       this.nomDept = nomDept;
       this.chefDept = chefDept;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomDept() {
        return this.nomDept;
    }
    
    public void setNomDept(String nomDept) {
        this.nomDept = nomDept;
    }
    public String getChefDept() {
        return this.chefDept;
    }
    
    public void setChefDept(String chefDept) {
        this.chefDept = chefDept;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    
    @Override
public String toString() {
    return String.valueOf(id);
}


    
   
}


