package pack;
// Generated 22 mai 2024 11:38:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private Depart depart;
     private String nom;
     private String prenom;
     private Date datenaiss;
     private String salaire;

    public Employee() {
    }

	
    public Employee(Depart depart) {
        this.depart = depart;
    }
    public Employee(Depart depart, String nom, String prenom, Date datenaiss, String salaire) {
       this.depart = depart;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaiss = datenaiss;
       this.salaire = salaire;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Depart getDepart() {
        return this.depart;
    }
    
    public void setDepart(Depart depart) {
        this.depart = depart;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }
    public String getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(String salaire) {
        this.salaire = salaire;
    }
    public Object getDepart_id() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


